version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    # Если нужны volume или env, добавь их ниже
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./dist:/usr/share/nginx/html:ro
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 